apiVersion: v2
actions:
  - name: "Run JMeter"
    events:
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "performance"
    tasks:
      - name: "Run jmeter perf tests"
        files:
          - jmeter/perf.jmx
        image: "core.harbor.domain/jmeter/jmeter:latest"
        args:
          - '-n'
          - '-t'
          - '/keptn/jmeter/perf.jmx'