apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "functest"
spec:
  stages:
    - name: "dev"
      sequences:
      - name: "delivery"
        tasks:
          - name: "deployment"
            properties:
              deploymentstrategy: "direct"
          - name: "test"
            properties:
              teststrategy: "functional"
          - name: "release"
    - name: "pvs"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "dev.delivery.finished"
            selector:
              match:
                result: pass
        tasks:
          - name: "deployment"
            properties:
              deploymentstrategy: "blue_green_service"
          - name: "test"
            properties:
              teststrategy: "performance"
          - name: "release"