apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.started
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"{{.data.project}} started"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: 1f2dcf8e-b4f2-4b0f-98e8-042f5f29e421
      sendFinished: false
      sendStarted: false
